version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: itzone123
      RABBITMQ_DEFAULT_PASS: 123
      RABBITMQ_DEFAULT_VHOST: itzone123-vhost

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"