server:
  port: 8082

logging:
  path: logs/
  level:
    root: info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  redis:
    host: localhost
    port: 6379