server:
  port: 9001

logging:
  path: logs/
  level:
    root: info

zuul:
  routes:
    city-service:
      path: /api/city-service/**
      serviceId: micro-weather-city-server
    weather-service:
      path: /api/weather-service/**
      serviceId: micro-weather-data-server